spring:
  application:
    name: adservice

  datasource:
    url: jdbc:h2:mem:ad_db;MODE=MariaDB  # MariaDB 호환 모드
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        enabled: true
        max-active: 100
        max-idle: 20
        min-idle: 10
        max-wait: 10000
    lock-expire-time: 5000

  jpa:
    hibernate:
      ddl-auto: none  # schema.sql을 사용할 것이므로 none으로 설정
    properties:
      hibernate:
        format_sql: true  # SQL 보기 좋게 출력
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

  lifecycle:
    timeout-per-shutdown-phase: 1m

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
